export const SERVICES = [
  {
    slug: "home-cleaning",
    ticket: "JOB-01",
    name: "Home Cleaning",
    tagline: "Deep clean, top to bottom",
    desc: "A trained two-person crew cleans kitchens, bathrooms, floors and windows with hospital-grade equipment.",
    price: "₹649",
    duration: "2–3 hrs",
    icon: "sparkles",
    image: "https://www.nobrokerhood.com/blog/wp-content/uploads/2024/12/NoBrokerHood-Home-Cleaning-Services.jpg",
    included: [
      "Two-person trained cleaning crew",
      "Hospital-grade equipment & eco-friendly agents",
      "Kitchen, bathroom, floor & window cleaning",
      "Free re-clean within 24 hours if you're not satisfied",
    ],
    
  },
  {
    slug: "salon-for-women",
    ticket: "JOB-02",
    name: "Salon at Home",
    tagline: "Studio-grade beauty, at your door",
    desc: "Facials, waxing, threading, manicure and haircuts, done with certified salon-grade products.",
    price: "₹499",
    duration: "60–90 min",
    icon: "scissors",
    image: "https://franckprovost.in/wp-content/uploads/2026/02/image-2.jpeg",
     included: [
      "Certified beauticians using salon-grade products",
      "Fresh, sanitized tool kit opened at your home",
      "Facials, waxing, threading, manicure & haircuts",
      "3-day touch-up guarantee on any service",
    ],
  },
  {
    slug: "ac-repair",
    ticket: "JOB-03",
    name: "AC Repair & Service",
    tagline: "Cool air, guaranteed",
    desc: "Gas top-up, deep foam cleaning, and diagnostics for split and window units, with a 30-day repair warranty.",
    price: "₹549",
    duration: "45–60 min",
    icon: "wind",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSbWNE2AStS7ZsPeBWGh0PvKcp9Pitr0od5UTV7wM4QmurE9hMaWb-zhv8&s=10",
    included: [
      "Certified AC technicians with diagnostic tools",
      "Gas top-up & deep foam coil cleaning",
      "Genuine spare parts only, priced upfront",
      "30-day warranty on every repair",
    ],
  },
  {
    slug: "plumbing",
    ticket: "JOB-04",
    name: "Plumbing",
    tagline: "Leaks, taps & fittings, fixed",
    desc: "Tap and pipe leak repair, bathroom fitting installation, and blockage clearing by licensed plumbers.",
    price: "₹199",
    duration: "30–45 min",
    icon: "wrench",
    image: "https://sc-cms-prod103-cdn-dsb5cvath4adbgd0.z01.azurefd.net/-/media/images/aerotek/business-insights/plumbing_career_social-jpg.jpg?rev=d535c3705c67442fb68fe4404fae26d1",
    included: [
      "Licensed, background-checked plumbers",
      "Common tools & spare parts carried on-site",
      "Leak repair, fitting installation & blockage clearing",
      "7-day workmanship warranty",
    ],
  },
  {
    slug: "electrician",
    ticket: "JOB-05",
    name: "Electrician",
    tagline: "Safe wiring, done right",
    desc: "Switchboard repair, fan and light installation, and wiring fixes from electricians who carry their own tools.",
    price: "₹149",
    duration: "20–40 min",
    icon: "zap",
    image: "https://media.istockphoto.com/id/1469656864/photo/electrician-engineer-uses-a-multimeter-to-test-the-electrical-installation-and-power-line.jpg?s=612x612&w=0&k=20&c=h70UOpNbJYT5G2oGT-KUeIE3yXwEgsCpr25yR1rnGtU=",
    included: [
      "Certified electricians with safety-tested tools",
      "Switchboard, wiring, fan & light installation",
      "Genuine parts with transparent, upfront pricing",
      "7-day workmanship warranty",
    ],
  },
  {
    slug: "painting",
    ticket: "JOB-06",
    name: "Home Painting",
    tagline: "Full-home painting, priced upfront",
    desc: "Pick your home size, paint finish, and whether you'd like us to supply the paint — see the full price before you book.",
    price: "from ₹8,999",
    duration: "1–4 days",
    icon: "paintbrush",
    image: "https://content.jdmagicbox.com/v2/comp/delhi/f5/011pxx11.xx11.230214100846.u2f5/catalogue/mr-yamin-malviya-nagar-delhi-1jaysumpcj.jpg",
    custom: true,
  },
];

export const getServiceBySlug = (slug) => SERVICES.find((s) => s.slug === slug);