export const SUB_SERVICES = {
  "home-cleaning": [
    {
      id: "kitchen-deep-clean",
      name: "Kitchen Deep Clean",
      desc: "Degreasing of chimney, tiles, countertops, and cabinet exteriors.",
      price: 399,
      duration: "60 min",
      image: "https://techsquadteam.com/assets/profile/blogimages/6628090e9797d9828a9f9032cd705113.jpg",
    },
    {
      id: "bathroom-deep-clean",
      name: "Bathroom Deep Clean",
      desc: "Descaling of tiles, fittings, and glass, plus a full sanitizing wipe-down.",
      price: 349,
      duration: "45 min",
      image: "https://deepcleaningservice.in/images/bathroom-deep-cleaning-services-providers-in-bangalore.png",
    },
    {
      id: "full-home-cleaning",
      name: "Full Home Cleaning (2 BHK)",
      desc: "Every room, floor to ceiling — the complete package for a move-in-ready home.",
      price: 899,
      duration: "3 hrs",
      image: "https://5.imimg.com/data5/SELLER/Default/2023/1/YT/OB/YL/81310128/full-home-cleaning-services.jpg",
    },
    {
      id: "sofa-carpet-cleaning",
      name: "Sofa & Carpet Cleaning",
      desc: "Shampoo wash and vacuum extraction for upholstery and carpets.",
      price: 599,
      duration: "60 min",
      image: "https://s3-ap-southeast-1.amazonaws.com/urbanclap-prod/images/growth/home-screen/1630420912606-2fffa6.jpeg",
    },
    {
      id: "window-balcony-cleaning",
      name: "Window & Balcony Cleaning",
      desc: "Glass, grills, and balcony floor cleaned and streak-free.",
      price: 249,
      duration: "30 min",
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR-r7EstOTE9PtLd3FDXvIEez4VbI8fpmTqgf7l87Ob1ZkILWmyS8wVWhuF&s=10",
    },
  ],
  "ac-repair": [
    {
      id: "ac-gas-topup",
      name: "AC Gas Top-up",
      desc: "Refrigerant top-up for units that aren't cooling properly.",
      price: 499,
      duration: "40 min",
      image: "https://5.imimg.com/data5/SELLER/Default/2023/8/335393699/TK/EE/WF/42540115/ac-gas-refilling-service.jpeg",
    },
    {
      id: "ac-service-split",
      name: "General Service (Split AC)",
      desc: "Foam-jet cleaning of the indoor and outdoor units.",
      price: 549,
      duration: "45 min",
      image: "https://techsquadteam.com/assets/profile/blogimages/b8c7da5cb0ab0ab4e62069608ff8f63f.jpg",
    },
    {
      id: "ac-service-window",
      name: "General Service (Window AC)",
      desc: "Full foam-jet cleaning and filter wash for window units.",
      price: 449,
      duration: "40 min",
      image: "https://www.pondicherryacrepairservices.com/assets/img/services/window-unit-services.webp",
    },
    {
      id: "ac-installation",
      name: "AC Installation",
      desc: "Mounting and installation of a new split or window unit.",
      price: 1199,
      duration: "90 min",
      image: "https://supersavvy.in/assets/images/acinstalltionblog.jpg",
    },
    {
      id: "ac-uninstallation",
      name: "AC Uninstallation",
      desc: "Safe removal of an existing unit, ready for relocation.",
      price: 499,
      duration: "45 min",
      image: "https://www.urbancompany.com/img/images/supply/customer-app-supply/1770745576900-b51eff.jpeg?bucket=urbanclap-prod&quality=90&format=auto&dpr=2",
    },
  ],
  plumbing: [
    {
      id: "tap-repair",
      name: "Tap Repair",
      desc: "Fixing leaky or dripping taps, washer and cartridge replacement.",
      price: 149,
      duration: "20 min",
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSgTXGxtUMIhsoK-cam5Rdvi13KB1kcKi5wLib_r7SI7pUdM7wUp_04jFA&s=10",
    },
    {
      id: "pipe-leak-fixing",
      name: "Pipe Leak Fixing",
      desc: "Locating and sealing leaks in exposed water pipes.",
      price: 249,
      duration: "30 min",
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQwASDHE1YmnwC-OmQ2vJUcveV8EuWGykK_QRigjPz22N5bATiy-fTOSQ&s=10",
    },
    {
      id: "toilet-repair",
      name: "Toilet / Cistern Repair",
      desc: "Fixing flush mechanisms, cisterns, and running toilets.",
      price: 299,
      duration: "30 min",
      image: "https://plumbingservice.co.in/images/services/a7.jpg",
    },
    {
      id: "bathroom-fitting",
      name: "Bathroom Fitting Installation",
      desc: "Installing new taps, showers, or washbasin fittings.",
      price: 399,
      duration: "45 min",
      image: "https://storage.googleapis.com/public-homes-web-media-prod/bathroom_fittings_2_4f7f1bfa15/bathroom_fittings_2_4f7f1bfa15.jpg",
    },
    {
      id: "drain-blockage",
      name: "Drain Blockage Clearing",
      desc: "Clearing clogged sinks, floor drains, and slow-draining pipes.",
      price: 349,
      duration: "40 min",
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRxEnQITP-le3QiMp8xwOTtRbtCgy-Fe5bV0MVbTRu6J_HNqaxa_cZzlfPH&s=10",
    },
  ],
  electrician: [
    {
      id: "switchboard-repair",
      name: "Switchboard Repair",
      desc: "Fixing faulty switches, sockets, and switchboard wiring.",
      price: 149,
      duration: "20 min",
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSlLgK2USO08bmW5qA2EkyOInFSXpb89Z01EMKtcNnfpHvm0lvGWsalWSDW&s=10",
    },
    {
      id: "fan-installation",
      name: "Fan Installation",
      desc: "Mounting and wiring a new ceiling or wall fan.",
      price: 199,
      duration: "30 min",
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSqjPeVwUYHxVi341rHzG5nxMXkGhHV8YGruPSQ0ympSWsZuzcc14YwCtY_&s=10",
    },
    {
      id: "light-installation",
      name: "Light Fixture Installation",
      desc: "Installing tube lights, LED panels, or decorative fixtures.",
      price: 179,
      duration: "25 min",
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTrHckSmu5UWwhvZTP1P3PAPpqxUf-TCuiQM6E18ZymtdjH14tBW8Ndc6c&s=10",
    },
    {
      id: "wiring-fault",
      name: "Wiring Fault Fixing",
      desc: "Diagnosing and repairing short circuits or faulty wiring runs.",
      price: 299,
      duration: "40 min",
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSfBENQ437vVTGW8UQvUeFDeVDV3kFJjAgQjNHMxvYDTtL-t2VSJKzt3MEw&s=10",
    },
    {
      id: "mcb-fuse-replacement",
      name: "MCB / Fuse Replacement",
      desc: "Replacing tripped MCBs or blown fuses in the main panel.",
      price: 249,
      duration: "25 min",
      image: "https://www.goldmedalindia.com/blog/wp-content/uploads/2025/04/Difference-between-Fuse-and-MCB.jpg",
    },
  ],
};

export const getSubServicesFor = (slug) => SUB_SERVICES[slug] || [];

export function formatINR(n) {
  return `₹${n.toLocaleString("en-IN")}`;
}